sftp:
  image: atmoz/sftp:latest
  # Expose port 22 inside the container as 2222 on your host
  ports:
    - "2222:22"
  volumes:
    - ./incoming:/incoming
    - ./archive:/archive
  # The 'command' sets up one or more SFTP users in the format:
  # "user[:password][:UID][:GID]:directory"
  # Here is where you define the username and password.
  command: "dev:0213:1001:1001:/incoming"
  # In this example:
  #    Username: alice
  #    Password: password
  #    UID: 1001, GID: 1001 (filesystem ownership)
  #    Home directory inside container: /incoming
